source 'http://rubygems.org'

gem 'rgss_tk'
gem 'activesupport',   '~> 4.1'
gem 'coffee-script',   '~> 2.3'
gem 'sass',            '~> 3.4'
gem 'sinatra',         '~> 1.4'
gem 'sinatra-contrib', '~> 1.4'
gem 'sinatra-partial', '~> 0.4'
gem 'slim',            '~> 2.0'
#gem 'tilt',            '~> 2.0'
gem 'puma'
gem 'yajl-ruby',       '~> 1.2'
